export const AUTHENTICATE_USER = "AUTHENTICATE_USER";

export const TOGGLE_RECIPE = "TOGGLE_RECIPE";
export const CLEAR_RECIPES = "CLEAR_RECIPES";
export const ADD_RECIPE = "ADD_RECIPE";
export const UPDATE_NEW_RECIPE_TITLE = "UPDATE_NEW_RECIPE_TITLE";
export const UPDATE_NEW_RECIPE_COOK_TIME = "UPDATE_NEW_RECIPE_COOK_TIME";
export const UPDATE_NEW_RECIPE_MEAL_TYPE = "UPDATE_NEW_RECIPE_MEAL_TYPE";
export const UPDATE_INGREDIENT_NAME = "UPDATE_INGREDIENT_NAME";
export const UPDATE_INGREDIENT_AMOUNT = "UPDATE_INGREDIENT_AMOUNT";
export const UPDATE_INGREDIENT_MEASUREMENT_TYPE =
  "UPDATE_INGREDIENT_MEASUREMENT_TYPE";
export const UPDATE_INSTRUCTION = "UPDATE_INSTRUCTION";
export const SET_RECIPES = "SET_RECIPES";

export const SET_GENERAL_BUDGET = "SET_GENERAL_BUDGET";
export const UPDATE_GENERAL_BANK_BUDGET = "UPDATE_GENERAL_BANK_BUDGET";
export const UPDATE_CREDIT_CARD = "UPDATE_CREDIT_CARD";

export const SET_MONTHLY_EXPENSES = "SET_MONTHLY_EXPENSES";
export const ADD_MONTHLY_EXPENSE = "ADD_MONTHLY_EXPENSE";
export const DELETE_MONTHLY_EXPENSE = "DELETE_MONTHLY_EXPENSE";

export const SET_PIGGY_BANKS = "SET_PIGGY_BANKS";
export const ADD_PIGGY_BANK = "ADD_PIGGY_BANK";
export const DELETE_PIGGY_BANK = "DELETE_PIGGY_BANK";

export const SET_INCOMES = "SET_INCOMES";
export const ADD_INCOME = "ADD_INCOME";
export const DELETE_INCOME = "DELETE_INCOME";

export const SET_MESSAGES = "SET_MESSAGES";
export const ADD_MESSAGE = "ADD_MESSAGE";
