export const TOGGLE_RECIPE = "TOGGLE_RECIPE";
export const CLEAR_RECIPES = "CLEAR_RECIPES";
export const ADD_RECIPE = "ADD_RECIPE";
export const UPDATE_NEW_RECIPE_TITLE = "UPDATE_NEW_RECIPE_TITLE";
export const UPDATE_NEW_RECIPE_COOK_TIME = "UPDATE_NEW_RECIPE_COOK_TIME";
export const UPDATE_NEW_RECIPE_MEAL_TYPE = "UPDATE_NEW_RECIPE_MEAL_TYPE";
export const UPDATE_INGREDIENT_NAME = "UPDATE_INGREDIENT_NAME";
export const UPDATE_INGREDIENT_AMOUNT = "UPDATE_INGREDIENT_AMOUNT";
export const UPDATE_INGREDIENT_MEASUREMENT_TYPE =
  "UPDATE_INGREDIENT_MEASUREMENT_TYPE";
export const UPDATE_INSTRUCTION = "UPDATE_INSTRUCTION";
