export const AUTHENTICATE_USER = "AUTHENTICATE_USER";

export const TOGGLE_RECIPE = "TOGGLE_RECIPE";
export const CLEAR_RECIPES = "CLEAR_RECIPES";
export const ADD_RECIPE = "ADD_RECIPE";
export const SET_RECIPES = "SET_RECIPES";

export const SET_GENERAL_BUDGET = "SET_GENERAL_BUDGET";
export const UPDATE_GENERAL_BANK_BUDGET = "UPDATE_GENERAL_BANK_BUDGET";
export const UPDATE_CREDIT_CARD = "UPDATE_CREDIT_CARD";

export const SET_MONTHLY_EXPENSES = "SET_MONTHLY_EXPENSES";
export const ADD_MONTHLY_EXPENSE = "ADD_MONTHLY_EXPENSE";
export const DELETE_MONTHLY_EXPENSE = "DELETE_MONTHLY_EXPENSE";

export const SET_PIGGY_BANKS = "SET_PIGGY_BANKS";
export const ADD_PIGGY_BANK = "ADD_PIGGY_BANK";
export const DELETE_PIGGY_BANK = "DELETE_PIGGY_BANK";

export const SET_INCOMES = "SET_INCOMES";
export const ADD_INCOME = "ADD_INCOME";
export const DELETE_INCOME = "DELETE_INCOME";

export const SET_MESSAGES = "SET_MESSAGES";
export const ADD_MESSAGE = "ADD_MESSAGE";

export const SET_USER_DATA = "SET_USER_DATA";
export const UPDATE_DISPLAY_NAME = "UPDATE_DISPLAY_NAME";
export const UPDATE_TEXT_COLOR = "UPDATE_TEXT_COLOR";
export const ADD_LINKED_EMAIL = "ADD_LINKED_EMAIL";
export const DELETE_LINKED_EMAIL = "DELETE_LINKED_EMAIL";
export const SET_PUSH_NOTIFICATIONS = "SET_PUSH_NOTIFICATIONS";

export const SET_PERSONAL_GOALS = "SET_PERSONAL_GOALS";
export const SET_PERSONAL_GOAL_COMPLETED = "SET_PERSONAL_GOAL_COMPLETED";
export const ADD_PERSONAL_GOAL = "ADD_PERSONAL_GOAL";
export const SET_PERSONAL_GOAL_ARCHIVED = "SET_PERSONAL_GOAL_ARCHIVED";
